// Copyright © 2026 Jalapeno Labs

// Generated by `anubis client generate-ts` from the OpenAPI document.
// Do not edit by hand. Regenerate after API changes.

// Utility
import ky from 'ky'

/** The fields a creative concept is created from, on both surfaces. */
export type CreateCreativeConceptBody = {
  /** Blank or absent stores no description. */
  description?: string | null
  name: string
}

/** The fields a granular detail is created from, on both surfaces. */
export type CreateGranularDetailBody = {
  /** Blank or absent stores no description. */
  description?: string | null
  name: string
}

/** The fields a tangible thing is created from, on both surfaces. */
export type CreateTangibleThingBody = {
  /** Blank or absent stores no description. */
  description?: string | null
  name: string
}

/** A creative concept, owned by a team. */
export type CreativeConcept = {
  /** When the creative concept was created. */
  created_at: string
  /** Optional long-form detail. */
  description?: string | null
  /** Primary key. */
  id: string
  /** Display name. */
  name: string
  /** The owning team; the whole ownership chain hangs off this column. */
  team_id: string
  /** When the creative concept was last updated, kept by the database trigger. */
  updated_at: string
}

/** One creative concept, as every endpoint that answers with one wraps it. */
export type CreativeConceptBody = {
  creative_concept: CreativeConceptView
}

/** A creative concept, as every endpoint serializes it. */
export type CreativeConceptView = CreativeConcept

/** A page of creative concepts, in the locked list envelope. */
export type CreativeConceptsBody = {
  creative_concepts: CreativeConceptView[]
  pagination: Pagination
}

/** The error shape every v1 endpoint answers with. */
export type ErrorV1 = {
  /** A user-safe description of what went wrong. */
  message: string
}

/** A granular detail, owned through its tangible thing. */
export type GranularDetail = {
  /** When the granular detail was created. */
  created_at: string
  /** Optional long-form detail. */
  description?: string | null
  /** Primary key. */
  id: string
  /** Display name. */
  name: string
  /** The parent tangible thing; the ownership chain continues through it. */
  tangible_thing_id: string
  /** When the granular detail was last updated, kept by the database trigger. */
  updated_at: string
}

/** One granular detail, as every endpoint that answers with one wraps it. */
export type GranularDetailBody = {
  granular_detail: GranularDetailView
}

/** A granular detail, as every endpoint serializes it. */
export type GranularDetailView = GranularDetail

/** A page of granular details, in the locked list envelope. */
export type GranularDetailsBody = {
  granular_details: GranularDetailView[]
  pagination: Pagination
}

/** The page a list response describes, beside its records. */
export type Pagination = {
  /** The page size in effect. */
  limit: number
  /** The page these records came from, 1-based. */
  page: number
  /** How many records match the query in total. */
  total_items: number
  /** How many pages the total spans; zero when nothing matches. */
  total_pages: number
}

/** A tangible thing, owned through its creative concept. */
export type TangibleThing = {
  /** When the tangible thing was created. */
  created_at: string
  /** The parent creative concept; the ownership chain continues through it. */
  creative_concept_id: string
  /** Optional long-form detail. */
  description?: string | null
  /** Primary key. */
  id: string
  /** Display name. */
  name: string
  /** When the tangible thing was last updated, kept by the database trigger. */
  updated_at: string
}

/** One tangible thing, as every endpoint that answers with one wraps it. */
export type TangibleThingBody = {
  tangible_thing: TangibleThingView
}

/** A tangible thing, as every endpoint serializes it. */
export type TangibleThingView = TangibleThing

/** A page of tangible things, in the locked list envelope. */
export type TangibleThingsBody = {
  pagination: Pagination
  tangible_things: TangibleThingView[]
}

/** Envelope for a single team. */
export type TeamEnvelopeV1 = {
  team: TeamV1
}

/** A team, as serialized by API v1. */
export type TeamV1 = {
  /** When the team was created. */
  created_at: string
  /** Primary key. */
  id: string
  /** Display name. */
  name: string
  /** The organization the team belongs to. */
  organization_id: string
}

/** The fields a creative concept is updated from, on both surfaces. */
export type UpdateCreativeConceptBody = {
  /** Blank clears the description, absent leaves it alone, which is exactly how the form behaves. */
  description?: string | null
  name?: string | null
}

/** The fields a granular detail is updated from, on both surfaces. */
export type UpdateGranularDetailBody = {
  /** Blank clears the description, absent leaves it alone, which is exactly how the form behaves. */
  description?: string | null
  name?: string | null
  /** Moves the granular detail to another tangible thing of the same team. */
  tangible_thing_id?: string | null
}

/** The fields a tangible thing is updated from, on both surfaces. */
export type UpdateTangibleThingBody = {
  /** Moves the tangible thing to another creative concept of the same team. */
  creative_concept_id?: string | null
  /** Blank clears the description, absent leaves it alone, which is exactly how the form behaves. */
  description?: string | null
  name?: string | null
}

type ClientOptions = {
  /** Path or URL the API is mounted under. Defaults to same-origin. */
  prefix?: string
  /** Platform application bearer token from the Developers section. */
  token: string
}

export function createAnubisV1(options: ClientOptions) {
  const client = ky.create({
    prefix: options.prefix ?? '/',
    retry: 0,
    headers: {
      authorization: `Bearer ${options.token}`,
    },
  })

  /** List the team's creative concepts. */
  async function listCreativeConcepts(): Promise<CreativeConceptsBody> {
    return client.get('api/v1/creative-concepts').json<CreativeConceptsBody>()
  }

  /** Create a creative concept in the token's team. */
  async function createCreativeConcept(body: CreateCreativeConceptBody): Promise<CreativeConceptBody> {
    return client.post('api/v1/creative-concepts', { json: body }).json<CreativeConceptBody>()
  }

  /** Fetch one creative concept. */
  async function showCreativeConcept(creativeConceptId: string): Promise<CreativeConceptBody> {
    return client.get(`api/v1/creative-concepts/${creativeConceptId}`).json<CreativeConceptBody>()
  }

  /** Update one creative concept. */
  async function updateCreativeConcept(
    creativeConceptId: string,
    body: UpdateCreativeConceptBody,
  ): Promise<CreativeConceptBody> {
    return client.patch(`api/v1/creative-concepts/${creativeConceptId}`, { json: body }).json<CreativeConceptBody>()
  }

  /** Delete one creative concept. */
  async function deleteCreativeConcept(creativeConceptId: string): Promise<void> {
    await client.delete(`api/v1/creative-concepts/${creativeConceptId}`)
  }

  /** List a creative concept's tangible things. */
  async function listTangibleThings(creativeConceptId: string): Promise<TangibleThingsBody> {
    return client.get(`api/v1/creative-concepts/${creativeConceptId}/tangible-things`).json<TangibleThingsBody>()
  }

  /** Create a tangible thing under a creative concept. */
  async function createTangibleThing(
    creativeConceptId: string,
    body: CreateTangibleThingBody,
  ): Promise<TangibleThingBody> {
    return client
      .post(`api/v1/creative-concepts/${creativeConceptId}/tangible-things`, { json: body })
      .json<TangibleThingBody>()
  }

  /** Fetch one granular detail. */
  async function showGranularDetail(granularDetailId: string): Promise<GranularDetailBody> {
    return client.get(`api/v1/granular-details/${granularDetailId}`).json<GranularDetailBody>()
  }

  /** Update one granular detail. */
  async function updateGranularDetail(
    granularDetailId: string,
    body: UpdateGranularDetailBody,
  ): Promise<GranularDetailBody> {
    return client.patch(`api/v1/granular-details/${granularDetailId}`, { json: body }).json<GranularDetailBody>()
  }

  /** Delete one granular detail. */
  async function deleteGranularDetail(granularDetailId: string): Promise<void> {
    await client.delete(`api/v1/granular-details/${granularDetailId}`)
  }

  /** Fetch one tangible thing. */
  async function showTangibleThing(tangibleThingId: string): Promise<TangibleThingBody> {
    return client.get(`api/v1/tangible-things/${tangibleThingId}`).json<TangibleThingBody>()
  }

  /** Update one tangible thing. */
  async function updateTangibleThing(
    tangibleThingId: string,
    body: UpdateTangibleThingBody,
  ): Promise<TangibleThingBody> {
    return client.patch(`api/v1/tangible-things/${tangibleThingId}`, { json: body }).json<TangibleThingBody>()
  }

  /** Delete one tangible thing. */
  async function deleteTangibleThing(tangibleThingId: string): Promise<void> {
    await client.delete(`api/v1/tangible-things/${tangibleThingId}`)
  }

  /** List a tangible thing's granular details. */
  async function listGranularDetails(tangibleThingId: string): Promise<GranularDetailsBody> {
    return client.get(`api/v1/tangible-things/${tangibleThingId}/granular-details`).json<GranularDetailsBody>()
  }

  /** Create a granular detail under a tangible thing. */
  async function createGranularDetail(
    tangibleThingId: string,
    body: CreateGranularDetailBody,
  ): Promise<GranularDetailBody> {
    return client
      .post(`api/v1/tangible-things/${tangibleThingId}/granular-details`, { json: body })
      .json<GranularDetailBody>()
  }

  /** The team the caller's token belongs to. */
  async function showTeam(): Promise<TeamEnvelopeV1> {
    return client.get('api/v1/team').json<TeamEnvelopeV1>()
  }

  return {
    listCreativeConcepts,
    createCreativeConcept,
    showCreativeConcept,
    updateCreativeConcept,
    deleteCreativeConcept,
    listTangibleThings,
    createTangibleThing,
    showGranularDetail,
    updateGranularDetail,
    deleteGranularDetail,
    showTangibleThing,
    updateTangibleThing,
    deleteTangibleThing,
    listGranularDetails,
    createGranularDetail,
    showTeam,
  } as const
}

export type AnubisV1 = ReturnType<typeof createAnubisV1>
