// Copyright © 2026 Jalapeno Labs

// Generated by `anubis billing generate-ts` from config/billing.yml.
// Do not edit by hand. Edit billing.yml and regenerate.

export type PlanKey =
  | 'free'
  | 'pro'

export type BillingInterval = 'monthly' | 'yearly'

export type PlanEnforcement = 'hard' | 'soft'

/** What one billing interval of a plan costs. */
export type PlanPrice = {
  stripePriceId: string
  /** In the currency's smallest unit: 2900 is $29.00. */
  amount: number
  /** Lowercase ISO 4217, as Stripe writes it. */
  currency: string
  /** True when the price is charged per seat rather than per organization. */
  perSeat: boolean
}

/**
 * What a plan allows of one metered thing.
 *
 * A limit a plan does not name is unlimited, so an absent key is not zero.
 * A `hard` limit refuses the create. A `soft` one allows it and warns.
 */
export type PlanLimit = {
  count: number
  enforcement: PlanEnforcement
}

export type Plan = {
  key: PlanKey
  name: string
  description: string | null
  /** True for the plan a pricing grid should make stand out. */
  highlighted: boolean
  /** True for the plan an organization with no subscription is on. */
  free: boolean
  prices: Partial<Record<BillingInterval, PlanPrice>>
  limits: Partial<Record<string, PlanLimit>>
}

/** Every plan, in the order config/billing.yml lists them. */
export const Plans = [
  {
    key: 'free',
    name: 'Free',
    description: 'Everything a small group needs to try the product.',
    highlighted: false,
    free: true,
    prices: {},
    limits: {
      creative_concepts: { count: 3, enforcement: 'hard' },
      seats: { count: 3, enforcement: 'hard' },
    },
  },
  {
    key: 'pro',
    name: 'Pro',
    description: 'For a team working together.',
    highlighted: true,
    free: false,
    prices: {
      monthly: {
        stripePriceId: 'price_replace_me_pro_monthly',
        amount: 2900,
        currency: 'usd',
        perSeat: true,
      },
      yearly: {
        stripePriceId: 'price_replace_me_pro_yearly',
        amount: 29000,
        currency: 'usd',
        perSeat: true,
      },
    },
    limits: {
      creative_concepts: { count: 100, enforcement: 'soft' },
      seats: { count: 25, enforcement: 'hard' },
    },
  },
] as const satisfies readonly Plan[]

/** The plan an organization with no subscription is on. */
export const FREE_PLAN_KEY: PlanKey = 'free'

/** The plan with this key, or undefined for one this build does not sell. */
export function findPlan(key: string): Plan | undefined {
  return Plans.find((plan) => plan.key === key)
}
