// Copyright © 2026 Jalapeno Labs

// Generated by `anubis roles generate-ts` from config/roles.yml.
// Do not edit by hand. Edit roles.yml and regenerate.

export type PermissionAction = 'read' | 'create' | 'update' | 'destroy'

export type RoleKey =
  | 'admin'
  | 'billing'
  | 'default'
  | 'editor'

export const RoleGrants = {
  admin: {
    CreativeConcept: [ 'read', 'create', 'update', 'destroy' ],
    GranularDetail: [ 'read', 'create', 'update', 'destroy' ],
    PeripheralNotion: [ 'read', 'create', 'update', 'destroy' ],
    TangibleThing: [ 'read', 'create', 'update', 'destroy' ],
  },
  billing: {
    CreativeConcept: [ 'read' ],
    GranularDetail: [ 'read' ],
    PeripheralNotion: [ 'read' ],
    TangibleThing: [ 'read' ],
  },
  default: {
    CreativeConcept: [ 'read' ],
    GranularDetail: [ 'read' ],
    PeripheralNotion: [ 'read' ],
    TangibleThing: [ 'read' ],
  },
  editor: {
    CreativeConcept: [ 'read', 'create', 'update', 'destroy' ],
    GranularDetail: [ 'read', 'create', 'update', 'destroy' ],
    PeripheralNotion: [ 'read', 'create', 'update', 'destroy' ],
    TangibleThing: [ 'read', 'create', 'update', 'destroy' ],
  },
} as const satisfies Record<RoleKey, Partial<Record<string, readonly PermissionAction[]>>>

// Widened view so arbitrary runtime role keys index safely.
const grantsByRole: Record<string, Partial<Record<string, readonly PermissionAction[]>> | undefined>
  = RoleGrants

export function can(
  heldRoles: readonly string[],
  action: PermissionAction,
  model: string,
): boolean {
  return heldRoles.some((role) => {
    const grants = grantsByRole[role]
    return Boolean(grants?.[model]?.includes(action))
  })
}
