//! `anubis new <name>`: stamp a fresh application from the embedded starter.
//!
//! The starter tree is embedded at build time (see `build.rs`), so stamping
//! is offline and always matches the installed framework version. Stamping
//! applies the app name across every path and file, then overlays the files
//! that make the result a standalone repository: a workspace `Cargo.toml`, a
//! standalone `backend/Cargo.toml` (the monorepo starter inherits from the
//! framework workspace), a root `package.json`, a CI workflow, the
//! development environment file, and the lint and toolchain pins. Until the
//! crate and npm package are published, stamped apps depend on the framework
//! straight from its git repository.
//!
//! The stamped Rust is then formatted, because rewriting the crate name moves
//! it within the `use` blocks the templates carry: `axum` sorts after `acme`
//! and before `zebra`, so no template order is right for every name. Without
//! the formatter a stamped application fails `cargo fmt --check` on its first
//! CI run.
//!
//! Stamped applications are private by default (`"license": "UNLICENSED"`,
//! no LICENSE file); `--license mit` writes an MIT LICENSE instead.

use std::path::Path;
use std::process::ExitCode;

use anubis::scaffold::Replacements;
use chrono::Datelike;
use clap::ValueEnum;

/// The embedded starter tree, generated by `build.rs`.
mod embedded {
    include!(concat!(env!("OUT_DIR"), "/starter_files.rs"));
}

/// Files layered on top of the stamped starter, as `(path, template)`.
///
/// Templates use the same `anubis-starter` vocabulary as the starter itself,
/// so one replacement pass stamps everything.
///
/// Both manifests are stored under prefixed names rather than as `Cargo.toml`.
/// Cargo's packager prunes any directory holding a `Cargo.toml`, taking it for
/// a nested package, and a pruned `templates/new` would ship a crate whose
/// `anubis new` cannot stamp anything.
const OVERLAY_FILES: [(&str, &str); 10] = [
    (
        "Cargo.toml",
        include_str!("../../templates/new/workspace-Cargo.toml"),
    ),
    (
        "backend/Cargo.toml",
        include_str!("../../templates/new/backend-Cargo.toml"),
    ),
    (
        "package.json",
        include_str!("../../templates/new/package.json"),
    ),
    (
        ".yarnrc.yml",
        include_str!("../../templates/new/yarnrc.yml"),
    ),
    (".gitignore", include_str!("../../templates/new/gitignore")),
    ("README.md", include_str!("../../templates/new/README.md")),
    (
        "rust-toolchain.toml",
        include_str!("../../templates/new/rust-toolchain.toml"),
    ),
    (
        "clippy.toml",
        include_str!("../../templates/new/clippy.toml"),
    ),
    (
        ".github/workflows/ci.yml",
        include_str!("../../templates/new/github-ci.yml"),
    ),
    (
        ".env.example",
        include_str!("../../templates/new/env.example"),
    ),
];

/// The MIT license `--license mit` writes, with `{year}` still to fill in.
const MIT_LICENSE: &str = include_str!("../../templates/new/LICENSE-mit");

/// The placeholder [`MIT_LICENSE`] carries in its copyright line.
const LICENSE_YEAR_PLACEHOLDER: &str = "{year}";

/// The development database password the templates carry, replaced at stamp
/// time so no two applications share one. It appears in `.env.example`, in
/// `compose.yaml`, and in the stamped CI workflow, all from this one token.
const TEMPLATE_DEV_PASSWORD: &str = "anubis-starter-dev-password";

/// The license a stamped application carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub(crate) enum License {
    /// Private application: `"license": "UNLICENSED"` and no LICENSE file.
    Unlicensed,
    /// MIT, with a LICENSE file to put your name in.
    Mit,
}

/// Stamps a new application into `./<name>` and reports the outcome.
pub(crate) fn run(name: &str, license: License) -> ExitCode {
    if let Err(reason) = validate_name(name) {
        eprintln!("error: {reason}");
        return ExitCode::FAILURE;
    }

    let target = Path::new(name);
    match target.read_dir() {
        Ok(mut entries) => {
            if entries.next().is_some() {
                eprintln!("error: directory `{name}` already exists and is not empty");
                return ExitCode::FAILURE;
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            eprintln!("error: cannot inspect `{name}`: {error}");
            return ExitCode::FAILURE;
        }
    }

    let replacements = replacements_for(name, license);
    let mut written = Vec::new();

    for (relative, bytes) in embedded::STARTER_FILES {
        let destination = target.join(replacements.apply(relative));
        let stamped = match std::str::from_utf8(bytes) {
            Ok(text) => replacements.apply(text).into_bytes(),
            // Binary assets copy through untouched.
            Err(_) => (*bytes).to_vec(),
        };
        if let Err(error) = write_file(&destination, &stamped) {
            eprintln!("error: {error}");
            return ExitCode::FAILURE;
        }
        written.push(destination);
    }

    for (relative, template) in OVERLAY_FILES {
        let destination = target.join(relative);
        let stamped = replacements.apply(template);
        if let Err(error) = write_file(&destination, stamped.as_bytes()) {
            eprintln!("error: {error}");
            return ExitCode::FAILURE;
        }
        written.push(destination);
    }

    if license == License::Mit {
        let year = chrono::Utc::now().year();
        let text = MIT_LICENSE.replace(LICENSE_YEAR_PLACEHOLDER, &year.to_string());
        let destination = target.join("LICENSE");
        if let Err(error) = write_file(&destination, text.as_bytes()) {
            eprintln!("error: {error}");
            return ExitCode::FAILURE;
        }
        written.push(destination);
    }

    // Settles where the new crate name sorts. See the module documentation.
    super::format_rust_files(&written);

    println!("created `{name}` ({} files)", written.len());
    println!();
    println!("Next steps:");
    println!("  cd {name}");
    println!("  git init");
    println!("  yarn install");
    println!("  yarn dev");
    println!();
    println!("`yarn dev` writes .env from .env.example on its first run.");
    println!("Commit Cargo.lock and yarn.lock too: they are what pin your dependencies.");
    if license == License::Mit {
        println!("Put your name in the LICENSE copyright line.");
    }
    ExitCode::SUCCESS
}

/// The name-and-wiring rewrites that turn the starter into `name`'s app.
fn replacements_for(name: &str, license: License) -> Replacements {
    // Display title from the kebab name, e.g. `acme-crm` becomes `Acme Crm`.
    let title = anubis::scaffold::Names::parse(name)
        .map_or_else(|_| name.to_owned(), |names| names.title());
    let mut pairs = vec![
        (
            "<title>Anubis</title>".to_owned(),
            format!("<title>{title}</title>"),
        ),
        (
            "\"title\": \"Anubis\"".to_owned(),
            format!("\"title\": \"{title}\""),
        ),
        (
            "The Anubis starter application frontend, stamped out by `anubis new`.".to_owned(),
            format!("The {name} frontend."),
        ),
        (
            "Anubis starter application".to_owned(),
            format!("{name} application"),
        ),
        (
            "anubis-starter-frontend".to_owned(),
            format!("{name}-frontend"),
        ),
        ("anubis-starter".to_owned(), name.to_owned()),
        // The Rust crate name of the backend library, as `main.rs` and the
        // integration tests import it.
        ("anubis_starter".to_owned(), name.replace('-', "_")),
        // Outside the monorepo the frontend package resolves from git until
        // it is published to npm.
        (
            "\"@jalapenolabs/anubis\": \"workspace:^\"".to_owned(),
            "\"@jalapenolabs/anubis\": \
             \"https://github.com/JalapenoLabs/Anubis.git#workspace=@jalapenolabs/anubis\""
                .to_owned(),
        ),
        // One fresh development database password per application, so no two
        // stamped apps ship the same default.
        (TEMPLATE_DEV_PASSWORD.to_owned(), development_password()),
    ];

    if license == License::Mit {
        pairs.push((
            "\"license\": \"UNLICENSED\"".to_owned(),
            "\"license\": \"MIT\"".to_owned(),
        ));
    }

    Replacements::new(pairs)
}

/// A fresh password for the stamped application's development database.
///
/// Ten random bytes in base32, which is 80 bits over an alphabet of letters
/// and digits only: no percent-encoding inside `DATABASE_URL`, no quoting in
/// YAML, and nothing a shell would look at twice. It guards a container bound
/// to localhost and is committed with the application, so it is a distinct
/// default rather than a real secret.
///
/// # Panics
/// Panics if the OS random source is unavailable, which would make every
/// other secret this command touches untrustworthy too.
fn development_password() -> String {
    let mut bytes = [0u8; 10];
    getrandom::fill(&mut bytes).expect("the OS random source must be available");
    data_encoding::BASE32_NOPAD.encode(&bytes)
}

/// Rejects names that would not work as a Cargo package, npm package, and
/// directory name all at once.
fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("the application name is empty".to_owned());
    }
    if !name.starts_with(|character: char| character.is_ascii_lowercase()) {
        return Err(format!("`{name}` must start with a lowercase ASCII letter"));
    }
    if let Some(bad) = name.chars().find(|character| {
        !character.is_ascii_lowercase() && !character.is_ascii_digit() && *character != '-'
    }) {
        return Err(format!(
            "`{name}` contains `{bad}`; use lowercase letters, digits, and hyphens"
        ));
    }
    if name.ends_with('-') {
        return Err(format!("`{name}` must not end with a hyphen"));
    }
    Ok(())
}

fn write_file(destination: &Path, contents: &[u8]) -> Result<(), String> {
    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    std::fs::write(destination, contents)
        .map_err(|error| format!("failed to write {}: {error}", destination.display()))
}

#[cfg(test)]
mod tests {
    use super::{
        License, OVERLAY_FILES, TEMPLATE_DEV_PASSWORD, embedded, replacements_for, validate_name,
    };

    /// The overlay template at `path`, which the list is expected to carry.
    fn overlay(path: &str) -> &'static str {
        let (_, template) = OVERLAY_FILES
            .iter()
            .find(|(candidate, _)| *candidate == path)
            .unwrap_or_else(|| panic!("the {path} overlay exists"));
        template
    }

    /// The starter-template file at `path`, as the binary embeds it.
    fn starter(path: &str) -> &'static str {
        let bytes = embedded::STARTER_FILES
            .iter()
            .find_map(|(candidate, bytes)| (*candidate == path).then_some(*bytes))
            .unwrap_or_else(|| panic!("the starter ships {path}"));
        std::str::from_utf8(bytes).unwrap_or_else(|_| panic!("{path} is UTF-8"))
    }

    /// A file at the repository root, read at test time.
    fn repository_file(relative: &str) -> String {
        let path = format!("{}/../{relative}", env!("CARGO_MANIFEST_DIR"));
        std::fs::read_to_string(&path).unwrap_or_else(|error| panic!("{path} is readable: {error}"))
    }

    #[test]
    fn names_are_validated() {
        validate_name("acme").unwrap();
        validate_name("acme-crm2").unwrap();
        validate_name("").unwrap_err();
        validate_name("Acme").unwrap_err();
        validate_name("9acme").unwrap_err();
        validate_name("acme_crm").unwrap_err();
        validate_name("acme-").unwrap_err();
    }

    #[test]
    fn the_embedded_starter_contains_the_essentials() {
        for expected in [
            "backend/Cargo.toml",
            "backend/src/main.rs",
            "backend/src/schema.rs",
            // The living templates ship with every stamped app.
            "backend/src/scaffolding/mod.rs",
            "backend/migrations/2026-08-11-000001_create_creative_concepts/up.sql",
            "config/roles.yml",
            "config/billing.yml",
            "compose.yaml",
            // The production image ships with every stamped app too.
            "Dockerfile",
            ".dockerignore",
            "frontend/package.json",
            "frontend/src/main.tsx",
            // The end-to-end suite ships with every stamped app.
            "frontend/playwright.config.ts",
            "frontend/e2e/global-setup.ts",
            "frontend/e2e/auth.spec.ts",
        ] {
            assert!(
                embedded::STARTER_FILES
                    .iter()
                    .any(|(path, _)| *path == expected),
                "starter template is missing {expected}",
            );
        }
    }

    #[test]
    fn stamping_leaves_no_starter_tokens_behind() {
        let replacements = replacements_for("acme", License::Unlicensed);
        for token in ["anubis-starter", "anubis_starter"] {
            for (path, bytes) in embedded::STARTER_FILES {
                let Ok(text) = std::str::from_utf8(bytes) else {
                    continue;
                };
                let stamped = replacements.apply(text);
                assert!(
                    !stamped.contains(token),
                    "{path} still contains `{token}` after stamping",
                );
            }
            for (path, template) in OVERLAY_FILES {
                let stamped = replacements.apply(template);
                assert!(
                    !stamped.contains(token),
                    "overlay {path} still contains `{token}` after stamping",
                );
            }
        }
    }

    /// The overlay backend manifest pins the same dependency versions as the
    /// framework workspace, so stamped apps compile against what the starter
    /// was tested with. Fails when a workspace bump forgets the template.
    #[test]
    fn overlay_dependency_versions_match_the_workspace() {
        let workspace = repository_file("Cargo.toml");
        let backend_template = overlay("backend/Cargo.toml");

        for dependency in [
            "axum",
            "chrono",
            "diesel",
            "diesel-async",
            "diesel_migrations",
            "http-body-util",
            "mimalloc",
            "serde",
            "serde_json",
            "tokio",
            "tower",
            "tracing",
            "tracing-subscriber",
            "utoipa",
            "uuid",
        ] {
            let workspace_line = workspace
                .lines()
                .find(|line| line.starts_with(&format!("{dependency} = ")))
                .unwrap_or_else(|| panic!("{dependency} is missing from the workspace manifest"));
            assert!(
                backend_template.lines().any(|line| line == workspace_line),
                "backend overlay pins `{dependency}` differently than the workspace \
                 (expected `{workspace_line}`)",
            );
        }
    }

    /// The stamped backend manifest renames the framework crate back to
    /// `anubis`, and renames the package this repository actually publishes.
    /// The library and the binary keep the plain name, which is what makes the
    /// rename invisible: applications write `use anubis::` and run `anubis`.
    #[test]
    fn the_overlay_renames_the_published_framework_crate() {
        let framework = repository_file("anubis/Cargo.toml");
        let published = manifest_name(&framework, "[package]");

        for (target, expected) in [("[lib]", "anubis"), ("[[bin]]", "anubis")] {
            assert_eq!(
                manifest_name(&framework, target),
                expected,
                "{target} carries the name every application types",
            );
        }

        let rename = format!("anubis = {{ package = \"{published}\",");
        assert!(
            overlay("backend/Cargo.toml").contains(&rename),
            "the backend overlay must declare `{rename} ... }}`",
        );

        // The stamped workflow installs the crate by its published name, and
        // gets the `anubis` binary out of it.
        let install = format!("cargo install {published} --git");
        assert!(
            overlay(".github/workflows/ci.yml").contains(&install),
            "the CI overlay must install the CLI with `{install} ...`",
        );
    }

    /// The value `name` takes in the manifest section `header` opens.
    fn manifest_name(manifest: &str, header: &str) -> String {
        manifest
            .lines()
            .skip_while(|line| line.trim() != header)
            .skip(1)
            .take_while(|line| !line.trim_start().starts_with('['))
            .find_map(|line| line.trim().strip_prefix("name = \""))
            .and_then(|rest| rest.split('"').next())
            .unwrap_or_else(|| panic!("{header} names a target"))
            .to_owned()
    }

    /// The stamped CI workflow pins the same tool versions as the framework's
    /// own, so a bump here reaches every application stamped afterwards.
    #[test]
    fn the_ci_overlay_pins_the_same_tool_versions_as_the_framework_workflow() {
        let workflow = repository_file(".github/workflows/ci.yml");
        let template = overlay(".github/workflows/ci.yml");

        for pin in [
            "image: postgres:17.6",
            "uses: dtolnay/rust-toolchain@",
            "node-version: ",
            "corepack prepare yarn@",
        ] {
            let pinned_line = workflow
                .lines()
                .map(str::trim)
                .find(|line| line.trim_start_matches("- ").starts_with(pin))
                .unwrap_or_else(|| panic!("the framework workflow pins `{pin}`"));
            assert!(
                template.lines().any(|line| line.trim() == pinned_line),
                "the CI overlay is missing the framework's pin `{pinned_line}`",
            );
        }
    }

    /// Every file the framework regenerates in CI is regenerated in a stamped
    /// application's CI too. Without this, a new generator would be checked for
    /// drift here and nowhere in the applications that ship it.
    #[test]
    fn the_ci_overlay_checks_every_generated_file_for_drift() {
        let template = overlay(".github/workflows/ci.yml");

        for (command, generated) in [
            ("roles generate-ts", "frontend/src/roles.generated.ts"),
            ("billing generate-ts", "frontend/src/plans.generated.ts"),
            ("client generate-ts", "frontend/src/api/v1.generated.ts"),
        ] {
            assert!(
                template.contains(command),
                "the CI overlay never runs `anubis {command}`",
            );
            assert!(
                template.contains(&format!("git diff --exit-code {generated}")),
                "the CI overlay never compares {generated}",
            );
        }
    }

    /// The stamped workflow runs the end-to-end suite the application ships,
    /// so the specs under `frontend/e2e/` are covered where they run rather
    /// than only in this repository.
    #[test]
    fn the_ci_overlay_runs_the_end_to_end_suite() {
        let template = overlay(".github/workflows/ci.yml");

        assert!(
            template.contains("playwright install --with-deps chromium"),
            "the CI overlay never provisions a browser",
        );
        assert!(
            template.contains("test:e2e"),
            "the CI overlay never runs the end-to-end suite",
        );
    }

    /// The repository's own `.env.example` is the template, unstamped: the
    /// monorepo runs the starter, so the two files describe the same app and
    /// must not drift.
    #[test]
    fn the_repository_env_example_matches_the_overlay() {
        assert_eq!(
            repository_file(".env.example").replace("\r\n", "\n"),
            overlay(".env.example").replace("\r\n", "\n"),
            "the repository .env.example and the `anubis new` overlay have drifted",
        );
    }

    /// The production image builds on the versions the rest of the repository
    /// pins. A bump that misses the Dockerfile would ship applications built by
    /// a compiler, a Node, or a Yarn that nothing else here ever ran.
    #[test]
    fn the_dockerfile_pins_what_the_rest_of_the_repository_pins() {
        let dockerfile = starter("Dockerfile");
        let toolchain = repository_file("rust-toolchain.toml");
        let workflow = repository_file(".github/workflows/ci.yml");

        let channel = toolchain
            .lines()
            .find_map(|line| line.trim().strip_prefix("channel = "))
            .expect("the toolchain file pins a channel")
            .trim_matches('"');
        assert!(
            dockerfile.contains(&format!("FROM rust:{channel}-")),
            "the Dockerfile does not build on rust {channel}",
        );

        let node = workflow
            .lines()
            .find_map(|line| line.trim().strip_prefix("node-version: "))
            .expect("the framework workflow pins a Node version");
        assert!(
            dockerfile.contains(&format!("FROM node:{node}-")),
            "the Dockerfile does not build on node {node}",
        );

        let yarn = workflow
            .lines()
            .map(str::trim)
            .find(|line| line.starts_with("corepack prepare yarn@"))
            .expect("the framework workflow pins a Yarn version");
        assert!(
            dockerfile.contains(yarn),
            "the Dockerfile is missing the framework's pin `{yarn}`",
        );
    }

    /// Every application gets its own development database password, and it
    /// reaches all three files that name one.
    #[test]
    fn stamping_replaces_the_template_development_password() {
        let replacements = replacements_for("acme", License::Unlicensed);

        for path in [".env.example", "compose.yaml", ".github/workflows/ci.yml"] {
            let template = match path {
                "compose.yaml" => starter(path),
                _ => overlay(path),
            };
            assert!(
                template.contains(TEMPLATE_DEV_PASSWORD),
                "{path} no longer carries the development password token",
            );
            assert!(
                !replacements.apply(template).contains(TEMPLATE_DEV_PASSWORD),
                "{path} still carries the template password after stamping",
            );
        }

        assert_ne!(
            replacements_for("acme", License::Unlicensed).apply(TEMPLATE_DEV_PASSWORD),
            replacements.apply(TEMPLATE_DEV_PASSWORD),
            "each stamp must mint its own password",
        );
    }

    /// Applications are private by default, and `--license mit` flips both the
    /// manifest field and the LICENSE file that goes with it.
    #[test]
    fn the_license_flag_drives_the_manifest_field() {
        let manifest = overlay("package.json");
        assert!(
            manifest.contains("\"license\": \"UNLICENSED\""),
            "the stamped manifest defaults to private",
        );

        let private = replacements_for("acme", License::Unlicensed).apply(manifest);
        assert!(private.contains("\"license\": \"UNLICENSED\""));

        let mit = replacements_for("acme", License::Mit).apply(manifest);
        assert!(mit.contains("\"license\": \"MIT\""), "got: {mit}");

        assert!(
            super::MIT_LICENSE.contains(super::LICENSE_YEAR_PLACEHOLDER),
            "the MIT template must carry its year placeholder",
        );
    }
}
