//! `anubis new <name>`: stamp a fresh application from the embedded starter.
//!
//! The starter tree is embedded at build time (see `build.rs`), so stamping
//! is offline and always matches the installed framework version. Stamping
//! applies the app name across every path and file, then overlays the files
//! that make the result a standalone repository: a workspace `Cargo.toml`, a
//! standalone `backend/Cargo.toml` (the monorepo starter inherits from the
//! framework workspace), a root `package.json`, and the lint and toolchain
//! pins. Until the crate and npm package are published, stamped apps depend
//! on the framework straight from its git repository.

use std::path::Path;
use std::process::ExitCode;

use anubis::scaffold::Replacements;

/// The embedded starter tree, generated by `build.rs`.
mod embedded {
    include!(concat!(env!("OUT_DIR"), "/starter_files.rs"));
}

/// Files layered on top of the stamped starter, as `(path, template)`.
///
/// Templates use the same `anubis-starter` vocabulary as the starter itself,
/// so one replacement pass stamps everything.
const OVERLAY_FILES: [(&str, &str); 8] = [
    ("Cargo.toml", include_str!("../../templates/new/Cargo.toml")),
    (
        "backend/Cargo.toml",
        include_str!("../../templates/new/backend-Cargo.toml"),
    ),
    (
        "package.json",
        include_str!("../../templates/new/package.json"),
    ),
    (
        ".yarnrc.yml",
        include_str!("../../templates/new/yarnrc.yml"),
    ),
    (".gitignore", include_str!("../../templates/new/gitignore")),
    ("README.md", include_str!("../../templates/new/README.md")),
    (
        "rust-toolchain.toml",
        include_str!("../../templates/new/rust-toolchain.toml"),
    ),
    (
        "clippy.toml",
        include_str!("../../templates/new/clippy.toml"),
    ),
];

/// Stamps a new application into `./<name>` and reports the outcome.
pub(crate) fn run(name: &str) -> ExitCode {
    if let Err(reason) = validate_name(name) {
        eprintln!("error: {reason}");
        return ExitCode::FAILURE;
    }

    let target = Path::new(name);
    match target.read_dir() {
        Ok(mut entries) => {
            if entries.next().is_some() {
                eprintln!("error: directory `{name}` already exists and is not empty");
                return ExitCode::FAILURE;
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            eprintln!("error: cannot inspect `{name}`: {error}");
            return ExitCode::FAILURE;
        }
    }

    let replacements = replacements_for(name);
    let mut written = 0_usize;

    for (relative, bytes) in embedded::STARTER_FILES {
        let destination = target.join(replacements.apply(relative));
        let stamped = match std::str::from_utf8(bytes) {
            Ok(text) => replacements.apply(text).into_bytes(),
            // Binary assets copy through untouched.
            Err(_) => (*bytes).to_vec(),
        };
        if let Err(error) = write_file(&destination, &stamped) {
            eprintln!("error: {error}");
            return ExitCode::FAILURE;
        }
        written += 1;
    }

    for (relative, template) in OVERLAY_FILES {
        let destination = target.join(relative);
        let stamped = replacements.apply(template);
        if let Err(error) = write_file(&destination, stamped.as_bytes()) {
            eprintln!("error: {error}");
            return ExitCode::FAILURE;
        }
        written += 1;
    }

    println!("created `{name}` ({written} files)");
    println!();
    println!("Next steps:");
    println!("  cd {name}");
    println!("  git init");
    println!("  yarn install");
    println!("  yarn dev");
    ExitCode::SUCCESS
}

/// The name-and-wiring rewrites that turn the starter into `name`'s app.
fn replacements_for(name: &str) -> Replacements {
    // Display title from the kebab name, e.g. `acme-crm` becomes `Acme Crm`.
    let title = anubis::scaffold::Names::parse(name)
        .map_or_else(|_| name.to_owned(), |names| names.title());
    Replacements::new([
        (
            "<title>Anubis</title>".to_owned(),
            format!("<title>{title}</title>"),
        ),
        (
            "\"title\": \"Anubis\"".to_owned(),
            format!("\"title\": \"{title}\""),
        ),
        (
            "The Anubis starter application frontend, stamped out by `anubis new`.".to_owned(),
            format!("The {name} frontend."),
        ),
        (
            "Anubis starter application".to_owned(),
            format!("{name} application"),
        ),
        (
            "anubis-starter-frontend".to_owned(),
            format!("{name}-frontend"),
        ),
        ("anubis-starter".to_owned(), name.to_owned()),
        // The Rust crate name of the backend library, as `main.rs` and the
        // integration tests import it.
        ("anubis_starter".to_owned(), name.replace('-', "_")),
        // Outside the monorepo the frontend package resolves from git until
        // it is published to npm.
        (
            "\"@jalapenolabs/anubis\": \"workspace:^\"".to_owned(),
            "\"@jalapenolabs/anubis\": \
             \"https://github.com/JalapenoLabs/Anubis.git#workspace=@jalapenolabs/anubis\""
                .to_owned(),
        ),
    ])
}

/// Rejects names that would not work as a Cargo package, npm package, and
/// directory name all at once.
fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("the application name is empty".to_owned());
    }
    if !name.starts_with(|character: char| character.is_ascii_lowercase()) {
        return Err(format!("`{name}` must start with a lowercase ASCII letter"));
    }
    if let Some(bad) = name.chars().find(|character| {
        !character.is_ascii_lowercase() && !character.is_ascii_digit() && *character != '-'
    }) {
        return Err(format!(
            "`{name}` contains `{bad}`; use lowercase letters, digits, and hyphens"
        ));
    }
    if name.ends_with('-') {
        return Err(format!("`{name}` must not end with a hyphen"));
    }
    Ok(())
}

fn write_file(destination: &Path, contents: &[u8]) -> Result<(), String> {
    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    std::fs::write(destination, contents)
        .map_err(|error| format!("failed to write {}: {error}", destination.display()))
}

#[cfg(test)]
mod tests {
    use super::{OVERLAY_FILES, embedded, replacements_for, validate_name};

    #[test]
    fn names_are_validated() {
        validate_name("acme").unwrap();
        validate_name("acme-crm2").unwrap();
        validate_name("").unwrap_err();
        validate_name("Acme").unwrap_err();
        validate_name("9acme").unwrap_err();
        validate_name("acme_crm").unwrap_err();
        validate_name("acme-").unwrap_err();
    }

    #[test]
    fn the_embedded_starter_contains_the_essentials() {
        for expected in [
            "backend/Cargo.toml",
            "backend/src/main.rs",
            "backend/src/schema.rs",
            // The living templates ship with every stamped app.
            "backend/src/scaffolding/mod.rs",
            "backend/migrations/2026-08-11-000001_create_creative_concepts/up.sql",
            "config/roles.yml",
            "compose.yaml",
            "frontend/package.json",
            "frontend/src/main.tsx",
        ] {
            assert!(
                embedded::STARTER_FILES
                    .iter()
                    .any(|(path, _)| *path == expected),
                "starter template is missing {expected}",
            );
        }
    }

    #[test]
    fn stamping_leaves_no_starter_tokens_behind() {
        let replacements = replacements_for("acme");
        for token in ["anubis-starter", "anubis_starter"] {
            for (path, bytes) in embedded::STARTER_FILES {
                let Ok(text) = std::str::from_utf8(bytes) else {
                    continue;
                };
                let stamped = replacements.apply(text);
                assert!(
                    !stamped.contains(token),
                    "{path} still contains `{token}` after stamping",
                );
            }
            for (path, template) in OVERLAY_FILES {
                let stamped = replacements.apply(template);
                assert!(
                    !stamped.contains(token),
                    "overlay {path} still contains `{token}` after stamping",
                );
            }
        }
    }

    /// The overlay backend manifest pins the same dependency versions as the
    /// framework workspace, so stamped apps compile against what the starter
    /// was tested with. Fails when a workspace bump forgets the template.
    #[test]
    fn overlay_dependency_versions_match_the_workspace() {
        let workspace =
            std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/../Cargo.toml"))
                .expect("the workspace manifest is readable");
        let (_, backend_template) = OVERLAY_FILES
            .iter()
            .find(|(path, _)| *path == "backend/Cargo.toml")
            .expect("the backend overlay exists");

        for dependency in [
            "axum",
            "chrono",
            "diesel",
            "diesel-async",
            "diesel_migrations",
            "http-body-util",
            "mimalloc",
            "serde",
            "serde_json",
            "tokio",
            "tower",
            "tracing",
            "tracing-subscriber",
            "utoipa",
            "uuid",
        ] {
            let workspace_line = workspace
                .lines()
                .find(|line| line.starts_with(&format!("{dependency} = ")))
                .unwrap_or_else(|| panic!("{dependency} is missing from the workspace manifest"));
            assert!(
                backend_template.lines().any(|line| line == workspace_line),
                "backend overlay pins `{dependency}` differently than the workspace \
                 (expected `{workspace_line}`)",
            );
        }
    }
}
