//! Renders a plan set as the generated TypeScript plan catalog.
//!
//! The frontend needs the plans to draw a pricing grid, and asking the API for
//! them would be a request for a file that was compiled into the same build.
//! So `anubis billing generate-ts` renders `config/billing.yml` into
//! `plans.generated.ts`, exactly as `anubis roles generate-ts` renders
//! permissions, and CI regenerates both and fails on a diff.
//!
//! The output follows the Jalapeno Labs TypeScript conventions (named exports,
//! `as const` tables, no semicolons) and is deterministic: the same
//! `billing.yml` always renders byte-identical TypeScript.

use std::fmt::Write;

use chrono::Datelike;

use super::plans::{Interval, Plan, PlanSet, Price};

pub(super) fn render(plans: &PlanSet) -> String {
    let year = chrono::Utc::now().year();
    let mut out = String::new();

    // The header matches the repository's license-header lint rule.
    let _ = writeln!(out, "// Copyright © {year} Jalapeno Labs");
    out.push_str(
        "\n\
         // Generated by `anubis billing generate-ts` from config/billing.yml.\n\
         // Do not edit by hand. Edit billing.yml and regenerate.\n\
         \n",
    );

    out.push_str("export type PlanKey =\n");
    for plan in plans.plans() {
        // Plan keys are validated as lowercase letters, digits, and
        // underscores, so they never need escaping or quoting as object keys.
        let _ = writeln!(out, "  | '{}'", plan.key());
    }
    out.push('\n');

    out.push_str(
        "export type BillingInterval = 'monthly' | 'yearly'\n\
         \n\
         export type PlanEnforcement = 'hard' | 'soft'\n\
         \n\
         /** What one billing interval of a plan costs. */\n\
         export type PlanPrice = {\n\
         \x20\x20stripePriceId: string\n\
         \x20\x20/** In the currency's smallest unit: 2900 is $29.00. */\n\
         \x20\x20amount: number\n\
         \x20\x20/** Lowercase ISO 4217, as Stripe writes it. */\n\
         \x20\x20currency: string\n\
         \x20\x20/** True when the price is charged per seat rather than per organization. */\n\
         \x20\x20perSeat: boolean\n\
         }\n\
         \n\
         /**\n\
         \x20* What a plan allows of one metered thing.\n\
         \x20*\n\
         \x20* A limit a plan does not name is unlimited, so an absent key is not zero.\n\
         \x20* A `hard` limit refuses the create. A `soft` one allows it and warns.\n\
         \x20*/\n\
         export type PlanLimit = {\n\
         \x20\x20count: number\n\
         \x20\x20enforcement: PlanEnforcement\n\
         }\n\
         \n\
         export type Plan = {\n\
         \x20\x20key: PlanKey\n\
         \x20\x20name: string\n\
         \x20\x20description: string | null\n\
         \x20\x20/** True for the plan a pricing grid should make stand out. */\n\
         \x20\x20highlighted: boolean\n\
         \x20\x20/** True for the plan an organization with no subscription is on. */\n\
         \x20\x20free: boolean\n\
         \x20\x20prices: Partial<Record<BillingInterval, PlanPrice>>\n\
         \x20\x20limits: Partial<Record<string, PlanLimit>>\n\
         }\n\
         \n\
         /** Every plan, in the order config/billing.yml lists them. */\n\
         export const Plans = [\n",
    );

    for plan in plans.plans() {
        render_plan(&mut out, plan);
    }

    out.push_str("] as const satisfies readonly Plan[]\n\n");

    let _ = write!(
        out,
        "/** The plan an organization with no subscription is on. */\n\
         export const FREE_PLAN_KEY: PlanKey = '{}'\n",
        plans.free().key(),
    );

    out.push_str(
        "\n\
         /** The plan with this key, or undefined for one this build does not sell. */\n\
         export function findPlan(key: string): Plan | undefined {\n\
         \x20\x20return Plans.find((plan) => plan.key === key)\n\
         }\n",
    );

    out
}

/// Renders one entry of the `Plans` array, indented two spaces.
fn render_plan(out: &mut String, plan: &Plan) {
    out.push_str("  {\n");
    let _ = writeln!(out, "    key: '{}',", plan.key());
    let _ = writeln!(out, "    name: '{}',", escape(plan.name()));
    match plan.description() {
        None => out.push_str("    description: null,\n"),
        Some(description) => {
            let _ = writeln!(out, "    description: '{}',", escape(description));
        }
    }
    let _ = writeln!(out, "    highlighted: {},", plan.is_highlighted());
    let _ = writeln!(out, "    free: {},", plan.is_free());

    if plan.prices().is_empty() {
        out.push_str("    prices: {},\n");
    } else {
        out.push_str("    prices: {\n");
        for (interval, price) in plan.prices() {
            render_price(out, *interval, price);
        }
        out.push_str("    },\n");
    }

    if plan.limits().is_empty() {
        out.push_str("    limits: {},\n");
    } else {
        out.push_str("    limits: {\n");
        for (name, limit) in plan.limits() {
            // Limit names carry the same shape as plan keys, so they are always
            // plain identifiers.
            let _ = writeln!(
                out,
                "      {name}: {{ count: {}, enforcement: '{}' }},",
                limit.count(),
                limit.enforcement(),
            );
        }
        out.push_str("    },\n");
    }

    out.push_str("  },\n");
}

fn render_price(out: &mut String, interval: Interval, price: &Price) {
    let _ = writeln!(out, "      {interval}: {{");
    let _ = writeln!(
        out,
        "        stripePriceId: '{}',",
        escape(price.stripe_price_id()),
    );
    let _ = writeln!(out, "        amount: {},", price.amount());
    let _ = writeln!(out, "        currency: '{}',", escape(price.currency()));
    let _ = writeln!(out, "        perSeat: {},", price.is_per_seat());
    out.push_str("      },\n");
}

/// Escapes a configured string for a single-quoted TypeScript literal.
fn escape(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use crate::billing::PlanSet;

    const BASELINE: &str = "
plans:
  - key: free
    name: Free
    description: Everything one person needs.
    limits:
      seats: 1
      projects:
        count: 3
        enforcement: soft
  - key: pro
    name: Pro
    highlighted: true
    prices:
      monthly:
        stripe_price_id: price_pro_monthly
        amount: 2900
        currency: usd
        per_seat: true
      yearly:
        stripe_price_id: price_pro_yearly
        amount: 29000
        currency: usd
    limits:
      seats: 25
";

    fn rendered() -> String {
        PlanSet::from_yaml(BASELINE)
            .expect("the baseline must parse")
            .to_typescript()
    }

    #[test]
    fn renders_the_keys_prices_limits_and_lookup() {
        let rendered = rendered();

        assert!(rendered.contains("| 'free'"), "got:\n{rendered}");
        assert!(rendered.contains("| 'pro'"), "got:\n{rendered}");
        assert!(rendered.contains("free: true,"), "got:\n{rendered}");
        assert!(rendered.contains("highlighted: true,"), "got:\n{rendered}");
        assert!(
            rendered.contains("stripePriceId: 'price_pro_monthly',"),
            "got:\n{rendered}",
        );
        assert!(rendered.contains("perSeat: true,"), "got:\n{rendered}");
        assert!(
            rendered.contains("seats: { count: 1, enforcement: 'hard' },"),
            "got:\n{rendered}",
        );
        assert!(
            rendered.contains("projects: { count: 3, enforcement: 'soft' },"),
            "got:\n{rendered}",
        );
        assert!(
            rendered.contains("export const FREE_PLAN_KEY: PlanKey = 'free'"),
            "got:\n{rendered}",
        );
        assert!(
            rendered.contains("export function findPlan("),
            "got:\n{rendered}",
        );
        assert!(!rendered.contains(';'), "no semicolons, got:\n{rendered}");
    }

    #[test]
    fn the_free_plan_carries_no_prices() {
        let rendered = rendered();

        assert!(rendered.contains("prices: {},"), "got:\n{rendered}");
        assert!(rendered.contains("description: null,"), "got:\n{rendered}");
    }

    #[test]
    fn configured_text_cannot_break_out_of_its_literal() {
        let plans = PlanSet::from_yaml(
            "
plans:
  - key: free
    name: \"Dave's \\\\ Free\"
    description: \"It's free\"
",
        )
        .expect("the plans must parse");

        let rendered = plans.to_typescript();

        assert!(
            rendered.contains(r"name: 'Dave\'s \\ Free',"),
            "got:\n{rendered}",
        );
        assert!(
            rendered.contains(r"description: 'It\'s free',"),
            "got:\n{rendered}",
        );
    }

    #[test]
    fn output_is_deterministic() {
        let plans = PlanSet::from_yaml(BASELINE).expect("the baseline must parse");

        assert_eq!(plans.to_typescript(), plans.to_typescript());
    }
}
