// Copyright © 2026 Jalapeno Labs

// Generated by `anubis client generate-ts` from the OpenAPI document.
// Do not edit by hand. Regenerate after API changes.

// Utility
import ky from 'ky'

/** The error shape every v1 endpoint answers with. */
export type ErrorV1 = {
  /** A user-safe description of what went wrong. */
  message: string
}

/** Envelope for a single team. */
export type TeamEnvelopeV1 = {
  team: TeamV1
}

/** A team, as serialized by API v1. */
export type TeamV1 = {
  /** When the team was created. */
  created_at: string
  /** Primary key. */
  id: string
  /** Display name. */
  name: string
  /** The organization the team belongs to. */
  organization_id: string
}

type ClientOptions = {
  /** Path or URL the API is mounted under. Defaults to same-origin. */
  prefix?: string
  /** Platform application bearer token from the Developers section. */
  token: string
}

export function createAnubisV1(options: ClientOptions) {
  const client = ky.create({
    prefix: options.prefix ?? '/',
    retry: 0,
    headers: {
      authorization: `Bearer ${options.token}`,
    },
  })

  /** The team the caller's token belongs to. */
  async function showTeam(): Promise<TeamEnvelopeV1> {
    return client.get('api/v1/team').json<TeamEnvelopeV1>()
  }

  return {
    showTeam,
  } as const
}

export type AnubisV1 = ReturnType<typeof createAnubisV1>
