//! Renders the OpenAPI document as the generated TypeScript client.
//!
//! The output follows the Jalapeno Labs TypeScript conventions (named
//! exports, no semicolons, ky for transport) and is deterministic: the same
//! OpenAPI document always renders byte-identical TypeScript, so CI can fail
//! on drift with a plain diff. Field names stay in wire form (`snake_case`)
//! because the generated types are the contract, not a view of it.
//!
//! The walker reads the document as JSON rather than utoipa's typed model,
//! so it keeps working as utoipa evolves and, later, when applications merge
//! scaffolded paths into the document.

use std::collections::BTreeMap;
use std::fmt::Write;

use chrono::Datelike;
use serde_json::Value;

/// HTTP methods the generator understands, in emission order.
const METHODS: [&str; 5] = ["get", "post", "put", "patch", "delete"];

pub(crate) fn render(document: &Value) -> String {
    let year = chrono::Utc::now().year();
    let mut out = String::new();

    let _ = writeln!(out, "// Copyright © {year} Jalapeno Labs");
    out.push_str(
        "\n\
         // Generated by `anubis client generate-ts` from the OpenAPI document.\n\
         // Do not edit by hand. Regenerate after API changes.\n\
         \n\
         // Utility\n\
         import ky from 'ky'\n\
         \n",
    );

    render_schemas(&mut out, document);
    render_client(&mut out, document);

    out
}

/// Emits one exported type per component schema, sorted by name.
fn render_schemas(out: &mut String, document: &Value) {
    let Some(schemas) = document
        .pointer("/components/schemas")
        .and_then(Value::as_object)
    else {
        return;
    };

    let sorted: BTreeMap<&String, &Value> = schemas.iter().collect();
    for (name, schema) in sorted {
        if let Some(description) = schema.get("description").and_then(Value::as_str) {
            let _ = writeln!(out, "/** {} */", comment(description));
        }
        let _ = writeln!(out, "export type {name} = {{");

        let required: Vec<&str> = schema
            .get("required")
            .and_then(Value::as_array)
            .map(|entries| entries.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let properties: BTreeMap<&String, &Value> = schema
            .get("properties")
            .and_then(Value::as_object)
            .map(|map| map.iter().collect())
            .unwrap_or_default();

        for (property, property_schema) in properties {
            if let Some(description) = property_schema.get("description").and_then(Value::as_str) {
                let _ = writeln!(out, "  /** {} */", comment(description));
            }
            let optional = if required.contains(&property.as_str()) {
                ""
            } else {
                "?"
            };
            let _ = writeln!(
                out,
                "  {}{optional}: {}",
                property,
                ts_type(property_schema)
            );
        }
        out.push_str("}\n\n");
    }
}

/// Emits the client factory with one function per operation.
fn render_client(out: &mut String, document: &Value) {
    out.push_str(
        "type ClientOptions = {\n\
         \x20\x20/** Path or URL the API is mounted under. Defaults to same-origin. */\n\
         \x20\x20prefix?: string\n\
         \x20\x20/** Platform application bearer token from the Developers section. */\n\
         \x20\x20token: string\n\
         }\n\
         \n\
         export function createAnubisV1(options: ClientOptions) {\n\
         \x20\x20const client = ky.create({\n\
         \x20\x20\x20\x20prefix: options.prefix ?? '/',\n\
         \x20\x20\x20\x20retry: 0,\n\
         \x20\x20\x20\x20headers: {\n\
         \x20\x20\x20\x20\x20\x20authorization: `Bearer ${options.token}`,\n\
         \x20\x20\x20\x20},\n\
         \x20\x20})\n\
         \n",
    );

    let mut function_names = Vec::new();

    let paths: BTreeMap<&String, &Value> = document
        .get("paths")
        .and_then(Value::as_object)
        .map(|map| map.iter().collect())
        .unwrap_or_default();

    for (path, item) in paths {
        for method in METHODS {
            let Some(operation) = item.get(method) else {
                continue;
            };
            function_names.push(render_operation(out, path, method, operation));
        }
    }

    out.push_str("  return {\n");
    for name in &function_names {
        let _ = writeln!(out, "    {name},");
    }
    out.push_str(
        "  } as const\n\
         }\n\
         \n\
         export type AnubisV1 = ReturnType<typeof createAnubisV1>\n",
    );
}

/// Emits one operation function and returns its name.
fn render_operation(out: &mut String, path: &str, method: &str, operation: &Value) -> String {
    let operation_id = operation
        .get("operationId")
        .and_then(Value::as_str)
        .unwrap_or("operation");
    let name = camel_case(operation_id);

    // Arguments: path parameters first, then the JSON body when present.
    let mut arguments = Vec::new();
    let mut path_params = Vec::new();
    if let Some(parameters) = operation.get("parameters").and_then(Value::as_array) {
        for parameter in parameters {
            let location = parameter.get("in").and_then(Value::as_str).unwrap_or("");
            let raw_name = parameter.get("name").and_then(Value::as_str).unwrap_or("");
            if location == "path" {
                let argument = camel_case(raw_name);
                let schema = parameter.get("schema").cloned().unwrap_or(Value::Null);
                arguments.push(format!("{argument}: {}", ts_type(&schema)));
                path_params.push((raw_name.to_owned(), argument));
            }
        }
    }

    let body_type = operation
        .pointer("/requestBody/content/application~1json/schema")
        .map(ts_type);
    if let Some(body_type) = &body_type {
        arguments.push(format!("body: {body_type}"));
    }

    let return_type = success_type(operation);

    if let Some(summary) = operation.get("summary").and_then(Value::as_str) {
        let _ = writeln!(out, "  /** {} */", comment(summary));
    }
    let _ = writeln!(
        out,
        "  async function {name}({}): Promise<{}> {{",
        arguments.join(", "),
        return_type.as_deref().unwrap_or("void"),
    );

    // Build the request path: template-literal when parameters interpolate.
    let mut request_path = path.trim_start_matches('/').to_owned();
    for (raw_name, argument) in &path_params {
        request_path =
            request_path.replace(&format!("{{{raw_name}}}"), &format!("${{{argument}}}"));
    }
    let quoted_path = if path_params.is_empty() {
        format!("'{request_path}'")
    } else {
        format!("`{request_path}`")
    };

    let request = if body_type.is_some() {
        format!("client.{method}({quoted_path}, {{ json: body }})")
    } else {
        format!("client.{method}({quoted_path})")
    };

    match &return_type {
        Some(rendered) => {
            let _ = writeln!(out, "    return {request}.json<{rendered}>()");
        }
        None => {
            let _ = writeln!(out, "    await {request}");
        }
    }
    out.push_str("  }\n\n");

    name
}

/// The TS type of the first 2xx JSON response, if any.
fn success_type(operation: &Value) -> Option<String> {
    let responses = operation.get("responses")?.as_object()?;
    let sorted: BTreeMap<&String, &Value> = responses.iter().collect();
    for (status, response) in sorted {
        if !status.starts_with('2') {
            continue;
        }
        if let Some(schema) = response.pointer("/content/application~1json/schema") {
            return Some(ts_type(schema));
        }
    }
    None
}

/// Maps a JSON schema fragment to a TypeScript type expression.
fn ts_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference.rsplit('/').next().unwrap_or("unknown").to_owned();
    }

    match schema.get("type") {
        Some(Value::String(kind)) => scalar_type(kind, schema),
        // OpenAPI 3.1 spells nullability as a type array, e.g. ["string", "null"].
        Some(Value::Array(kinds)) => {
            let mut parts: Vec<String> = kinds
                .iter()
                .filter_map(Value::as_str)
                .map(|kind| {
                    if kind == "null" {
                        "null".to_owned()
                    } else {
                        scalar_type(kind, schema)
                    }
                })
                .collect();
            parts.dedup();
            parts.join(" | ")
        }
        _other => "unknown".to_owned(),
    }
}

fn scalar_type(kind: &str, schema: &Value) -> String {
    match kind {
        "string" => "string".to_owned(),
        "integer" | "number" => "number".to_owned(),
        "boolean" => "boolean".to_owned(),
        "array" => {
            let items = schema.get("items").map_or("unknown".to_owned(), ts_type);
            format!("{items}[]")
        }
        "object" => "Record<string, unknown>".to_owned(),
        other => {
            tracing::debug!(
                schema.kind = other,
                "unmapped OpenAPI type {{schema.kind}}; emitting unknown",
            );
            "unknown".to_owned()
        }
    }
}

fn camel_case(raw: &str) -> String {
    let mut result = String::new();
    for (index, part) in raw
        .split(['_', '-'])
        .filter(|part| !part.is_empty())
        .enumerate()
    {
        if index == 0 {
            result.push_str(part);
        } else {
            let mut characters = part.chars();
            if let Some(first) = characters.next() {
                result.extend(first.to_uppercase());
                result.push_str(characters.as_str());
            }
        }
    }
    result
}

/// Keeps a description safe inside a single-line block comment.
fn comment(raw: &str) -> String {
    raw.replace("*/", "*\\/").replace(['\r', '\n'], " ")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::api::v1;

    fn rendered() -> String {
        let document = serde_json::to_value(v1::openapi()).expect("the document must serialize");
        render(&document)
    }

    #[test]
    fn renders_types_operations_and_the_factory() {
        let output = rendered();

        assert!(output.contains("export type TeamV1 = {"), "got:\n{output}");
        assert!(output.contains("organization_id: string"), "got:\n{output}");
        assert!(
            output.contains("export function createAnubisV1(options: ClientOptions) {"),
            "got:\n{output}"
        );
        assert!(
            output.contains("async function showTeam(): Promise<TeamEnvelopeV1> {"),
            "got:\n{output}"
        );
        assert!(
            output.contains("client.get('api/v1/team').json<TeamEnvelopeV1>()"),
            "got:\n{output}"
        );
        assert!(output.contains("showTeam,"), "got:\n{output}");
        assert!(!output.contains(';'), "no semicolons, got:\n{output}");
    }

    #[test]
    fn output_is_deterministic() {
        assert_eq!(rendered(), rendered());
    }
}
