//! Renders a resolved role set as the generated TypeScript module.
//!
//! The output follows the Jalapeno Labs TypeScript conventions (named
//! exports, `as const` lookup tables, no semicolons) and is deterministic:
//! the same roles.yml always renders byte-identical TypeScript, so CI can
//! fail on drift with a plain diff.

use std::collections::BTreeMap;
use std::fmt::Write;

use chrono::Datelike;

use crate::roles::ModelGrants;

pub(crate) fn render(resolved: &BTreeMap<String, ModelGrants>) -> String {
    let year = chrono::Utc::now().year();
    let mut out = String::new();

    // The header matches the repository's license-header lint rule.
    let _ = writeln!(out, "// Copyright © {year} Jalapeno Labs");
    out.push_str(
        "\n\
         // Generated by `anubis roles generate-ts` from config/roles.yml.\n\
         // Do not edit by hand. Edit roles.yml and regenerate.\n\
         \n\
         export type PermissionAction = 'read' | 'create' | 'update' | 'destroy'\n\
         \n",
    );

    out.push_str("export type RoleKey =\n");
    for role in resolved.keys() {
        let _ = writeln!(out, "  | '{}'", escape(role));
    }
    out.push('\n');

    out.push_str("export const RoleGrants = {\n");
    for (role, grants) in resolved {
        if grants.is_empty() {
            let _ = writeln!(out, "  {}: {{}},", key(role));
            continue;
        }
        let _ = writeln!(out, "  {}: {{", key(role));
        for (model, actions) in grants {
            let rendered_actions = actions
                .iter()
                .map(|action| format!("'{}'", action.as_str()))
                .collect::<Vec<_>>()
                .join(", ");
            // House style pads array literals: `[ 'read' ]`, not `['read']`.
            let _ = writeln!(out, "    {}: [ {rendered_actions} ],", key(model));
        }
        out.push_str("  },\n");
    }
    out.push_str(
        "} as const satisfies Record<RoleKey, Partial<Record<string, readonly PermissionAction[]>>>\n\
         \n",
    );

    out.push_str(
        "// Widened view so arbitrary runtime role keys index safely.\n\
         const grantsByRole: Record<string, Partial<Record<string, readonly PermissionAction[]>> | undefined>\n\
         \x20\x20= RoleGrants\n\
         \n\
         export function can(\n\
         \x20\x20heldRoles: readonly string[],\n\
         \x20\x20action: PermissionAction,\n\
         \x20\x20model: string,\n\
         ): boolean {\n\
         \x20\x20return heldRoles.some((role) => {\n\
         \x20\x20\x20\x20const grants = grantsByRole[role]\n\
         \x20\x20\x20\x20return Boolean(grants?.[model]?.includes(action))\n\
         \x20\x20})\n\
         }\n",
    );

    out
}

/// Renders an object key, quoting only when it is not a plain identifier.
fn key(raw: &str) -> String {
    let plain_identifier = !raw.is_empty()
        && raw
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_alphabetic() || first == '_' || first == '$')
        && raw.chars().all(|character| {
            character.is_ascii_alphanumeric() || character == '_' || character == '$'
        });

    if plain_identifier {
        raw.to_owned()
    } else {
        format!("'{}'", escape(raw))
    }
}

fn escape(raw: &str) -> String {
    raw.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use crate::roles::RoleSet;

    const BASELINE: &str = "
roles:
  default:
    models:
      Project: [read]
  admin:
    includes: [default]
    models:
      Project: [manage]
  billing:
    models: {}
";

    #[test]
    fn renders_role_keys_grants_and_the_can_helper() {
        let set = RoleSet::from_yaml(BASELINE).expect("baseline must parse");
        let rendered = set.to_typescript();

        assert!(rendered.contains("| 'admin'"), "got:\n{rendered}");
        assert!(rendered.contains("| 'billing'"), "got:\n{rendered}");
        assert!(
            rendered.contains("Project: [ 'read', 'create', 'update', 'destroy' ],"),
            "got:\n{rendered}"
        );
        assert!(rendered.contains("billing: {},"), "got:\n{rendered}");
        assert!(
            rendered.contains("export function can("),
            "got:\n{rendered}"
        );
        assert!(!rendered.contains(';'), "no semicolons, got:\n{rendered}");
    }

    #[test]
    fn output_is_deterministic() {
        let set = RoleSet::from_yaml(BASELINE).expect("baseline must parse");
        assert_eq!(set.to_typescript(), set.to_typescript());
    }
}
